spring:
  datasource:
    url: jdbc:mysql://localhost:3306/InterviewPrepAppDatabase?useSSL=false&serverTimezone=UTC
    username: root
    password: {password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


server:
  port: 8080

# JWT Configuration
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 3600000  # 1 hour in milliseconds (3600000 = 1 hour)

excel:
  import:
    sheet-id = sheet_id

google:
  credentials:
    file = classpath:credentials.json

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data.redis: DEBUG